name: API CI/CD

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  packages: write

jobs:
  APIs-cicd:
    uses: mairie360/CICD/.github/workflows/APIs_cicd.yml@main
    permissions:
          contents: write
          packages: write
          id-token: write
    with:
      postman_collection: ${{ vars.POSTMAN_MESSAGE_API_COLLECTION_ID }} #change api name
      postman_environment: ${{ vars.POSTMAN_MESSAGE_API_ENV_ID }} #change api name
      package_name: message-api #change api name
    secrets: inherit
